sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t dd1331/movement-server-test -f Dockerfile.dev .

script:
  # - docker run -e CI=true dd1331/movement-server-test npm run test -- --coverage

after_success:
  - echo "test succeed!"
  - docker build -t dd1331/movement-server Dockerfile ./

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "DOCKER_HUB_ID" --password-stdin

  - docker push dd1331/movement-server

