version: "3"
services: 
#  nginx:
#   restart: always
#   build: 
#    dockerfile: Dockerfile
#    context: ./nginx
#   ports: 
#    - "3000:80"

   # for local enviroment
   # mysql:
   #    image: "mysql:5.7.24"
   #    # build: ./mysql
   #    container_name: "typeorm-mysql"
   #    ports:
   #       - "3306:3306"
   #       # volumes: 
   #          # - ./mysql/mysql_data:/var/lib/mysql
   #          # - ./mysql/sqls/:/docker-entrypoint-initdb.d/
   #    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
   #    environment:
   #       MYSQL_ROOT_PASSWORD: "a9884592"
   #       MYSQL_USER: "charlie"
   #       MYSQL_PASSWORD: "1331"
   #       MYSQL_DATABASE: "movement"

   redis:
      image: "redis"
      container_name: redis-server
      ports:
         - "6379:6379"

   backend:
      build: 
         dockerfile: Dockerfile
         context: ./
      ports:
         - "3000:3000"
      container_name: movement-server
      volumes: 
         - /app/node_modules
         - ./:/app
      # for aws
      environment: 
         MYSQL_HOST: mysql
         MYSQL_USER: root
         MYSQL_ROOT_PASSWORD: a9884592
         MYSQL_DATABASE: movement
         MYSQL_PORT: 3306
   